services:
  ptacik:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ptacik 
    restart: unless-stopped
    env_file:
      - .env
    command: python src/main.py

    tty: true
    stdin_open: true